# Site settings
title: OpenAstronomy
email: openastronomy@googlegroups.com
description: > # this means to ignore newlines until "baseurl:"
  Where all about the combined force of different open source projects
  in astronomy and astrophysics takes place.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://openastronomy.github.io" # the base hostname & protocol for your site
#twitter_username: None
github_username:  openastronomy
irc_channel: openastronomy@freenode

# Build settings
markdown: kramdown

members: [members/astropy.html, members/sunpy.html]

#missions: [missions/gsoc2015.html]
collections:
  missions:
     output: true